In [0]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import count,sum,avg,min,mean,max

In [0]:
spark = SparkSession.builder.appName("Office").getOrCreate()

In [0]:
df = spark.read.options(inferSchema=True,header=True,delimeter=',').csv('/FileStore/tables/StudentData.csv')
df.show()

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 28|  Male|  Celeste Lollis|    PF| 21267|   45|Jeannetta Golden_...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|  Male|  Sheryll Towler|   DSA| 41487|   41|Claude Panos_Judi...|
| 28|  Male|  Margene Moores|   MVC| 52771|   32|Toshiko Hillyard_...|
| 28|  Male|     Neda Briski|   OOP| 61973|   69|Alberta Freund_El...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 28|  Male|  Celeste Lollis|   MVC| 81492|   64|Nicole Harwood_Cl...|
| 29|  Male|  Cordie Harnois|   OOP| 92882|   51|Judie Chipps_Clem...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
| 29|  Male| Ernest Rossbach|    DB|111449|   53|Maybell Duguay_Ab...|
| 28|Female|  Latia Vanhoose|    DB|122502|   27|Latia Vanhoose_Mi...|
| 29|Female|  Latia Vanhoose|   MVC|132110|   55|Eda Neathery_Nico...|
| 29|  Male|     Neda Briski|    PF|141770|   42|Margene Moores_Mi...|
| 29|Female|  Latia Vanhoose|    DB|152159|   27|Claude Panos_Sant...|
| 29|  Male|  Loris Crossett|   MVC|161771|   36|Mitzi Seldon_Jenn...|
| 29|  Male|  Annika Hoffman|   OOP|171660|   22|Taryn Brownlee_Mi...|
| 29|  Male|   Santa Kerfien|    PF|182129|   56|Judie Chipps_Tary...|
| 28|Female|Mickey Cortright|    DB|192537|   62|Ernest Rossbach_M...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 20 rows

In [0]:
df.printSchema()

root
 |-- employee_name: string (nullable = true)
 |-- department: string (nullable = true)
 |-- state: string (nullable = true)
 |-- salary: integer (nullable = true)
 |-- age: integer (nullable = true)
 |-- bonus: integer (nullable = true)

In [0]:
df.orderBy('bonus').show(10)
# or
df.sort(df.bonus.asc()).show(10)

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
+-------------+----------+-----+------+---+-----+

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Raman|   Finance|   CA| 99000| 40|24000|
+-------------+----------+-----+------+---+-----+

In [0]:
df.sort(df.age.desc(),df.salary.asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [0]:
df.sort(df.age.desc(),df.bonus.desc(),df.salary.asc()).show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|      Michael|     Sales|   NY| 86000| 56|20000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|        Raman|   Finance|   CA| 99000| 40|24000|
|        Scott|   Finance|   NY| 83000| 36|19000|
|        James|     Sales|   NY| 90000| 34|10000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

In [0]:
# to perform groupBy you must perform someother opertation to on it else it will give an error

In [0]:
df.groupBy("department","state").count().show()

+----------+-----+-----+
|department|state|count|
+----------+-----+-----+
|   Finance|   NY|    2|
| Marketing|   NY|    1|
|     Sales|   CA|    1|
| Marketing|   CA|    1|
|   Finance|   CA|    2|
|     Sales|   NY|    2|
+----------+-----+-----+

In [0]:
df.withColumn("Inhand Salary", ((df.salary - df.bonus)/13)*12).show()

+-------------+----------+-----+------+---+-----+------------------+
|employee_name|department|state|salary|age|bonus|     Inhand Salary|
+-------------+----------+-----+------+---+-----+------------------+
|        James|     Sales|   NY| 90000| 34|10000| 73846.15384615384|
|      Michael|     Sales|   NY| 86000| 56|20000| 60923.07692307692|
|       Robert|     Sales|   CA| 81000| 30|23000|53538.461538461546|
|        Maria|   Finance|   CA| 90000| 24|23000| 61846.15384615385|
|        Raman|   Finance|   CA| 99000| 40|24000| 69230.76923076923|
|        Scott|   Finance|   NY| 83000| 36|19000| 59076.92307692308|
|          Jen|   Finance|   NY| 79000| 53|15000| 59076.92307692308|
|         Jeff| Marketing|   CA| 80000| 25|18000|57230.769230769234|
|        Kumar| Marketing|   NY| 91000| 50|21000| 64615.38461538462|
+-------------+----------+-----+------+---+-----+------------------+

In [0]:
df.groupBy('department').agg(count('*').alias('count'),sum('salary').alias('salary'),sum('bonus').alias("bonus")).show()

+----------+-----+------+-----+
|department|count|salary|bonus|
+----------+-----+------+-----+
|     Sales|    3|257000|53000|
|   Finance|    4|351000|81000|
| Marketing|    2|171000|39000|
+----------+-----+------+-----+

In [0]:
df.groupBy('department').sum().show()
# or 
df.groupBy('department').sum('salary').show()

+----------+-----------+--------+----------+
|department|sum(salary)|sum(age)|sum(bonus)|
+----------+-----------+--------+----------+
|     Sales|     257000|     120|     53000|
|   Finance|     351000|     153|     81000|
| Marketing|     171000|      75|     39000|
+----------+-----------+--------+----------+

+----------+-----------+
|department|sum(salary)|
+----------+-----------+
|     Sales|     257000|
|   Finance|     351000|
| Marketing|     171000|
+----------+-----------+

In [0]:
df.groupBy('gender').count().show()

+------+-----+
|gender|count|
+------+-----+
|Female|  501|
|  Male|  499|
+------+-----+

In [0]:
df.filter(df.marks>50).groupBy('gender').count().show()

+------+-----+
|gender|count|
+------+-----+
|Female|  310|
|  Male|  320|
+------+-----+

In [0]:
df1=df.filter(df.gender=='Female')
df1.show(5)

+---+------+----------------+------+------+-----+--------------------+
|age|gender|            name|course|  roll|marks|               email|
+---+------+----------------+------+------+-----+--------------------+
| 28|Female| Hubert Oliveras|    DB|  2984|   59|Annika Hoffman_Na...|
| 29|Female|Toshiko Hillyard| Cloud| 12899|   62|Margene Moores_Ma...|
| 29|Female|    Elenore Choy|    DB| 32877|   29|Billi Clore_Mitzi...|
| 28|Female|    Claude Panos| Cloud| 72409|   85|Sheryll Towler_Al...|
| 29|Female|       Kena Wild|   DSA|102285|   35|Dustin Feagins_Ma...|
+---+------+----------------+------+------+-----+--------------------+
only showing top 5 rows

In [0]:
df2 = df1.groupBy(df1.course,df1.name).agg(count('*'))
df2.show()

+------+------------------+--------+
|course|              name|count(1)|
+------+------------------+--------+
|    PF|   Ernest Rossbach|       2|
| Cloud|Priscila Tavernier|       1|
|    PF|   Marylee Capasso|       1|
|   OOP|    Dustin Feagins|       2|
|   DSA|      Naoma Fritts|       2|
|   MVC|    Taryn Brownlee|       4|
| Cloud|  Jeannetta Golden|       3|
| Cloud|    Jalisa Swenson|       4|
|    PF|    Loris Crossett|       4|
|   MVC|   Sebrina Maresca|       2|
| Cloud|       Abram Nagao|       3|
|    PF|      Judie Chipps|       2|
|   MVC|      Naoma Fritts|       3|
|   MVC|   Marylee Capasso|       1|
|   DSA|    Taryn Brownlee|       1|
| Cloud|       Donna Yerby|       1|
|   MVC|  Toshiko Hillyard|       2|
|    PF|      Cheri Kenney|       2|
|   OOP|    Melani Engberg|       2|
|    DB|    Sheryll Towler|       3|
+------+------------------+--------+
only showing top 20 rows

In [0]:
df.groupBy(df.course).count().show()

+------+-----+
|course|count|
+------+-----+
|    PF|  166|
|    DB|  157|
|   MVC|  157|
|   DSA|  176|
| Cloud|  192|
|   OOP|  152|
+------+-----+

In [0]:
df.groupBy(df.course,df.gender).count().show()

+------+------+-----+
|course|gender|count|
+------+------+-----+
|   OOP|  Male|   70|
|    DB|  Male|   82|
| Cloud|Female|  106|
|   MVC|  Male|   86|
|   DSA|Female|   98|
|    PF|  Male|   97|
|   MVC|Female|   71|
| Cloud|  Male|   86|
|    PF|Female|   69|
|   DSA|  Male|   78|
|    DB|Female|   75|
|   OOP|Female|   82|
+------+------+-----+

In [0]:
df.groupBy(df.course,df.gender).sum('marks').show()

+------+------+----------+
|course|gender|sum(marks)|
+------+------+----------+
|   OOP|  Male|      4234|
|    DB|  Male|      5073|
| Cloud|Female|      6316|
|   MVC|  Male|      5241|
|   DSA|Female|      6124|
|    PF|  Male|      5960|
|   MVC|Female|      4344|
| Cloud|  Male|      5127|
|    PF|Female|      3973|
|   DSA|  Male|      4826|
|    DB|Female|      4197|
|   OOP|Female|      4682|
+------+------+----------+

In [0]:
df.groupBy(df.course,df.age).agg(min('marks'),max('marks'),avg('marks')).show()

+------+---+----------+----------+------------------+
|course|age|min(marks)|max(marks)|        avg(marks)|
+------+---+----------+----------+------------------+
|   MVC| 28|        23|        99| 60.44444444444444|
|   MVC| 29|        22|        99| 61.56470588235294|
| Cloud| 28|        20|        99|             58.08|
|    PF| 29|        20|        99|56.275862068965516|
|    PF| 28|        20|        98| 63.75949367088607|
|   OOP| 29|        20|        99|59.729729729729726|
|   DSA| 28|        20|        99|  64.6867469879518|
| Cloud| 29|        21|        98|             61.25|
|    DB| 28|        21|        98| 58.76829268292683|
|   DSA| 29|        20|        99| 60.01075268817204|
|   OOP| 28|        23|        99| 57.64102564102564|
|    DB| 29|        20|        98|59.346666666666664|
+------+---+----------+----------+------------------+